import {
  Image,
  ImageBackground,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import React, { useState } from 'react';
import AntDesign from 'react-native-vector-icons/AntDesign';
import BottomNav from '../Components/BottomNav';

const DashBoard = ({navigation}) => {

const [open, setOpen] = useState(false)


  return (
    <View style={{flex: 1}}>
      <StatusBar backgroundColor="#ffffff" />
      <ScrollView>
        <View style={styles.NavContainer}>
          <Image
            source={require('../assets/Glads.png')}
            style={{height: 50, width: 50, marginLeft: '4%'}}
          />
          <Text style={styles.NavText}>Dashboard</Text>
        </View>

        <View style={{height: 90, backgroundColor: '#fa7452'}}>
          <View style={{flexDirection: 'row'}}>
            <View style={styles.AvtarStyle}>
              <Image
                source={require('../assets/Avtar.png')}
                style={styles.AvtarImage}
              />
            </View>

            <Text
              style={{
                marginLeft: 24,
                fontSize: 20,
                fontWeight: '500',
                color: '#ffffff',
                marginTop: '5%',
              }}>
              Hii ! Staff Member
            </Text>
          </View>
          <Text
            style={{
              marginLeft: '25%',
              marginTop: '-6%',
              fontWeight: '400',
              color: '#ffffff',
              fontSize: 15,
            }}>
            ID: 3866626354343
          </Text>
        </View>

        <View style={{marginHorizontal: '10%'}}>
          <Text
            style={{
              fontSize: 22,
              fontWeight: '500',
              color: '#fa7452',
              marginVertical: '5%',
            }}>
            Enter Bill Number
          </Text>
        </View>

        <View style={styles.inputContainer}>
          <TextInput
            placeholder="Enter Bill Number"
            style={styles.InputStyle}
          />
          <TouchableOpacity onPress={()=> setOpen(!open)}>
            <AntDesign
              name="rightcircle"
              size={30}
              color="#fa7452"
              style={{marginRight: 8}}
            />
          </TouchableOpacity>
        </View>

        <View
          style={{
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: '10%',
          }}>
          <ImageBackground
            source={require('../assets/Logo.png')}
            style={{
              width: '100%',
              height: 360,
              opacity: 0.1,
            }}></ImageBackground>
        </View>


        
        {
            open ? (

        <TouchableOpacity activeOpacity={0.9} onPress={()=>navigation.navigate('Form')} >
          <View
            style={[{
              flexDirection: 'row',
              backgroundColor: '#ffffff',
              elevation: 3,
              justifyContent: 'space-evenly',
              marginTop: '-90%',
              marginHorizontal: '8%',
              paddingVertical: '10%',
              borderRadius: 12,
              // display: 'none'
            },]}>
            <View>
              <Text
                style={{
                  fontSize: 16,
                  fontWeight: '400',
                  color: '#000000',
                  marginTop: '0%',
                }}>
                Bill Number <Text style={{}}> : 84735535</Text>{' '}
              </Text>
              <Text
                style={{
                  fontSize: 16,
                  fontWeight: '400',
                  color: '#000000',
                  marginTop: '8%',
                }}>
                Generated By <Text style={{}}>: 84735</Text>{' '}
              </Text>
              <Text
                style={{
                  fontSize: 16,
                  fontWeight: '400',
                  color: '#000000',
                  marginTop: '8%',
                }}>
                Status <Text style={{color: '#67d545'}}>: Cleared</Text>{' '}
              </Text>
            </View>

            <View>
              <Image
                source={{
                  uri: 'https://img.freepik.com/premium-photo/blank-backboard-background_24076-517.jpg',
                }}
                style={{height: 80, width: 80}}
              />
            </View>
          </View>
        </TouchableOpacity>

            ) : null
          
        }



      </ScrollView>

      <BottomNav navigation={navigation} />
    </View>
  );
};

export default DashBoard;

const styles = StyleSheet.create({
  NavContainer: {
    backgroundColor: '#ffffff',
    elevation: 9,
    paddingVertical: '2%',
    flexDirection: 'row',
    alignItems: 'center',
  },

  NavText: {
    fontSize: 24,
    color: '#000000',
    fontWeight: '500',
    marginLeft: '16%',
  },

  inputContainer: {
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: '10%',
    backgroundColor: '#ffffff',
  },

  InputStyle: {
    width: '80%',
    fontWeight: '400',
    fontSize: 16,
    marginLeft: 8,
  },

  AvtarImage: {
    height: 60,
    width: 60,
  },

  AvtarStyle: {
    height: 60,
    width: 60,
    borderRadius: 60,
    borderWidth: 1,
    marginTop: 14,
    marginLeft: 5,
    borderColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
